# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# name: Deploy to Lightsail

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#   runs-on: ubuntu-latest

#   steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Set up SSH
#       uses: webfactory/ssh-agent@v0.5.3
#       with:
#         ssh-private-key: ${{ secrets.LIGHTSAIL_SSH_KEY }}

#     - name: Deploy to Lightsail
#       env:
#         LIGHTSAIL_IP: ${{ secrets.LIGHTSAIL_IP }}
#       run: |
#         ssh -o StrictHostKeyChecking=no USER@$LIGHTSAIL_IP 'bash -s' << 'EOF'
#           cd /caminho/da/sua/aplicacao
#           git pull origin main
#           npm install
#           pm2 reload all # ou o nome específico da aplicação se configurado
#         EOF
